language: node_js
node_js:
  - '8'
  - '10'
  - '12'

install:
  - npm install

script:
  - npm test
  - npm run lint
  - npm run build

after_script:
  - npm run codecov

deploy:
  provider: npm
  skip_cleanup: true
  email: publish@snowplowanalytics.com
  api_key: $NPM_TOKEN
  on:
    tags: true
