language: node_js
node_js:
  - '9'
  - '8'
  - '7'
  - '6'

install:
  - npm install

script:
  - npm test

after_script:
  - npm run codecov

deploy:
  provider: npm
  email: publish@snowplowanalytics.com
  api_key: $NPM_TOKEN
  on:
    tags: true
